<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-02-16T21:33:20+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Factorian',
        ],
    ],
];
